//This file is used to generate titles of campgrounds...
module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Waterfall',
    'Village',
    'Hills',
    'Point',
    'Group Camp',
    'Horse Camp',
    'Ghost Camp',
    'Camp',
    'Greenery',
    'TouristPoint',
    'River',
    'Dam',
    'Forest',
    'Wildlife Sanctuary',
    'Monsoon',
    'Friends Park',
    'Desert',
    'Baug',
    'Hunting valley',
    'Reverse Waterfall',
    'Springs'
]